version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:00"
      timezone: "Australia/Melbourne"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:00"
      timezone: "Australia/Melbourne"

  - package-ecosystem: "pip"
    directory: "/"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:00"
      timezone: "Australia/Melbourne"
