services:
  package:
    build:
      context: .
      secrets:
        - github_token
    volumes:
      - ./src:/package/src
      - ./tests:/package/tests
    ports:
      - "8002:80"

secrets:
  github_token:
    environment: GITHUB_TOKEN
