FROM python:3.14.0-slim

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Configure ENV
ENV PYTHONBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    LOGGING_CONFIG_LEVEL=INFO \
    LOGGING_CONFIG_NAMESPACES='["", "uvicorn"]' \
    DATABASE_TYPE=SQL_ALCHEMY \
    DATABASE_SQL_ALCHEMY_URL=sqlite+aiosqlite:////package/data/data.db \
    ALEMBIC_AUTO_MIGRATE_DB_URL=sqlite:////package/data/data.db \
    ALEMBIC_AUTO_MIGRATE_INI_PATH=/package/alembic.ini \
    ALEMBIC_AUTO_MIGRATE_SCRIPT_LOCATION=/package/alembic \
    ALEMBIC_AUTO_MIGRATE_AUTOGENERATE=true \
    ALEMBIC_AUTO_MIGRATE_MIGRATION_MESSAGE="autogenerated at startup" \
    ALEMBIC_AUTO_MIGRATE_COMPARE_TYPE=true \
    ALEMBIC_AUTO_MIGRATE_COMPARE_SERVER_DEFAULT=true \
    ALEMBIC_AUTO_MIGRATE_INCLUDE_SCHEMAS=false

# Directory for package
WORKDIR /package

# Install project dependencies (ensures cache before project change)
COPY pyproject.toml tox.ini README.md .

# Inject a temporary .netrc from a build secret and run uv
RUN uv sync --no-install-project

# Install remaining project
COPY src ./src
COPY tests ./tests
COPY alembic ./alembic
COPY alembic.ini ./alembic.ini
RUN mkdir -p /package/data

# Install the project
RUN uv sync

# Default entrypoint for running FastAPI services
ENTRYPOINT ["uv", "run", "uvicorn"]
CMD ["ab_service.user.main:app", "--host", "0.0.0.0", "--port", "80"]
