services:
  service:
    build:
      context: .

    volumes:
      - ./src:/package/src
      - ./tests:/package/tests
      - ./alembic:/package/alembic
      - ./alembic.ini:/package/alembic.ini:ro
      - data:/package/data

    ports:
      - "8002:80"

volumes:
  data:
