"""autogenerated at startup.

Revision ID: e541301cf557
Revises: f7a4aacac705
Create Date: 2026-03-08 08:23:23.136430
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e541301cf557'
down_revision: Union[str, None] = 'f7a4aacac705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_constraint('uq_users_oidc', type_='unique')
        batch_op.drop_index('ix_users_oidc_sub')
        batch_op.create_index('ix_users_oidc_sub', ['oidc_sub'], unique=True)
        batch_op.create_unique_constraint('uq_users_oidc_sub', ['oidc_sub'])
        batch_op.drop_column('oidc_iss')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('oidc_iss', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint('uq_users_oidc_sub', type_='unique')
        batch_op.drop_index('ix_users_oidc_sub')
        batch_op.create_index('ix_users_oidc_sub', ['oidc_sub'], unique=False)
        batch_op.create_unique_constraint('uq_users_oidc', ['oidc_iss', 'oidc_sub'])
    # ### end Alembic commands ###
