name: CI

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches: [main]

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }} - ci-pipeline"
  cancel-in-progress: true

jobs:
  lint:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on:
      group: Default
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      # Install uv + Python (with cache)
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: latest
          enable-cache: true
          python-version: "3.12"

      # Private Git deps (optional; remove if not needed)
      - name: Configure Git credentials for private deps
        if: env.GH_READ_TOKEN != ''
        env:
          GH_READ_TOKEN: ${{ secrets.GH_READ_TOKEN }}
        run: |
          git config --global url."https://${GH_READ_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Sync deps
        run: uv sync --extra all

      - name: Lint
        run: uv run tox -e lint

  test:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on:
      group: Default
    timeout-minutes: 5
    # Run in parallel with lint (remove this 'needs' to keep parallel; add needs: [lint] to serialize)
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: latest
          enable-cache: true
          python-version: "3.12"

      - name: Configure Git credentials for private deps
        if: env.GH_READ_TOKEN != ''
        env:
          GH_READ_TOKEN: ${{ secrets.GH_READ_TOKEN }}
        run: |
          git config --global url."https://${GH_READ_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Sync deps
        run: uv sync --extra all

      - name: Test
        run: uv run tox -e test
