name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

permissions: read-all

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.head_ref || github.ref }} - release"
  cancel-in-progress: true

jobs:
  publish:
    runs-on: 
      group: Default
    timeout-minutes: 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Install project Python
      run: uv python install

    - name: Build
      run: uv build --no-sources

    - name: Publish to PyPI
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.UV_PUBLISH_TOKEN }}
      run: uv publish --verbose